train_data:
  DB_dir: "../data/all_emb_1"
  min_hh_size: 2
  max_hh_size: 8
  household_size: 500
  hh_num: 1000
  guests_per_hh: 250
  enrollment_utt: 4
  evaluation_utt: 10
  random_batch : false
eval_data:
  DB_dir: "../data/all_emb_1"
  min_hh_size: 2
  max_hh_size: 4
  household_size: 250
  hh_num: 1000
  guests_per_hh: 125
  enrollment_utt: 4
  evaluation_utt: 10
  random_batch : false
scoring_model:
  input_dropout_rate: 0.5
  adaptation_input_features: 256
  adaptation_output_features: 32
  use_bias: true
training:
  batch_size: 1000
  epoch_num: 10
  num_workers: 16
  learning_rate: 1e-2